version: '3.8'

services:
  mangopost_api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: mangopost_api
    expose:
      - "8080"
    restart: unless-stopped
    env_file:
      - ../env/.env.mangopost
    volumes:
      - ../volumes/mangopost/token.json:/app/gmail/token.json
      - ../volumes/mangopost/last_checked.json:/app/gmail/last_checked.json
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - local

networks:
  local:
    external: true
    name: deploy_local




